apiVersion: skaffold/v4beta2
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: balchu/boink
    ko:
      dependencies:
        paths:
        - "**/*.go"
        - go.*  
manifests:
  rawYaml:
    - manifest/rbac.yaml
    - manifest/nginx-cron-starter.yaml
    - manifest/nginx-cron-stopper.yaml