apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: nginx-starter
  namespace: test
spec:
  #this is in UTC
  schedule: "46 6 * * *"
  startingDeadlineSeconds: 10
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:      
      template:
        spec:
          serviceAccountName: boink
          containers:
          - name: boink
            image: balchu/boink:0.1-alpha-10-g5d04a1e-dirty
            command: ["/boink"]
            args: ["--namespace","test", "--label", "app=nginx", "--action" , "start"]
          restartPolicy: OnFailure