apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: nginx-stopper
  namespace: test
spec:
  #this is in UTC
  schedule: "43 6 * * *"
  startingDeadlineSeconds: 10
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:      
      template:
        spec:
          serviceAccountName: boink
          containers:
          - name: boink
            image: boink:1.0
            command: ["/boink"]
            args: ["--namespace","test", "--label", "app=nginx", "--action" , "stop"]
          restartPolicy: OnFailure